name: 'Deploy App'

on:
  workflow_dispatch:
    inputs:
      backend-ref:
        required: true
        default: main
      ui-ref:
        required: true
        default: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: bastikempken/power-data
          path: backend
          ref: ${{inputs.backend-ref}}
      - name: Get backend commit sha
        id: backend-commit-sha
        run: |
          BACKEND_SHA=$(git -C backend log -1 --format=%h)
          echo "sha=$BACKEND_SHA" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
        with:
          repository: bastikempken/power-data-ui
          path: ui
          ref: ${{inputs.ui-ref}}
      - name: Get ui commit sha
        id: ui-commit-sha
        run: |
          UI_SHA=$(git -C ui log -1 --format=%h)
          echo "sha=$UI_SHA" >> "$GITHUB_OUTPUT"
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: fuchsrot/power-data
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: fuchsrot/power-data:${{ steps.backend-commit-sha.outputs.sha }}-${{ steps.ui-commit-sha.outputs.sha }},fuchsrot/power-data:latest
          labels: ${{ steps.meta.outputs.labels }}