name: 'Deploy App'

on:
  workflow_dispatch:
    inputs:
      app-ref:
        required: true
        default: main
      ui-ref:
        required: true
        default: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: bastikempken/power-data
          path: app
          ref: ${{inputs.app-ref}}
      - name: Get backend commit sha
        id: app-commit-sha
        run: |
          SHA=$(git -C app log -1 --format=%h)
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
        with:
          repository: bastikempken/power-data-ui
          path: ui
          ref: ${{inputs.ui-ref}}
      - name: Get ui commit sha
        id: ui-commit-sha
        run: |
          SHA=$(git -C ui log -1 --format=%h)
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"
      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
        with:
          platforms: linux/amd64,linux/arm64
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: fuchsrot/power-data:${{ steps.app-commit-sha.outputs.sha }}-${{ steps.ui-commit-sha.outputs.sha }},fuchsrot/power-data:latest